---
title: "Bibliometrix Analysis"
date: "`r Sys.time()`"
output:
  html_document:
    df_print: paged
author: Yufei Li
---

```{r setup, include=FALSE, echo=TRUE, warning = FALSE}
# include = FALSE prevents code and results from appearing in the finished file. R Markdown still runs the code in the chunk, and the results can be used by other chunks.
# echo = FALSE prevents code, but not the results from appearing in the finished file. This is a useful way to embed figures.
# message = FALSE prevents messages that are generated by code from appearing in the finished file.
# warning = FALSE prevents warnings that are generated by code from appearing in the finished.
# fig.cap = "..." adds a caption to graphical results.

knitr::opts_chunk$set(include = FALSE, echo = FALSE, warning=FALSE, message=FALSE)
# {r, , include = TRUE, echo=FALSE, fig.cap = "..."}
# {r, , include = TRUE, echo=FALSE}
```

```{r, loading packages}
packages <- c("bibliometrix",
              "dplyr",
              "citr")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))
  lapply(packages, library, character.only = TRUE)
} else {
  lapply(packages, library, character.only = TRUE)
}
remove(packages)
```

```{r}
#Combine plain text files, because web of science can only export 500 references at once
M <- c("savedrecs.txt") %>% 
  #Read file into R using convert2df(file= , dbsource ="", format = "")
  convert2df(file = ., dbsource = "wos", format = "plaintext") #Creates a bibliographic data frame
# http://htmlpreview.github.io/?https://github.com/massimoaria/bibliometrix/master/vignettes/bibliometrix-vignette.html

```

```{r}
results <- biblioAnalysis(M, sep = ";")
# print(results)
options(width=100)
Summary_results <- summary(object = results, k = 10, pause = FALSE)
# Choosing k=10 you decide to see the first 10 Authors, the first 10 sources, etc.
# print(Summary_results)
```

```{r, Graphic summarys of results, include = TRUE, echo=FALSE}
# print("Graphic summarys of results")
plot(x = results, k = 10, pause = FALSE)
```

```{r, include = TRUE, echo=FALSE}
print("10 most frequent cited manuscripts")
# To obtain the 10 most frequent cited manuscripts:
CR <- citations(M, field = "article", sep = ";")
cbind(CR$Cited[1:10])

```

```{r, include = TRUE, echo=FALSE}
print("10 most frequent cited first authors")
# To obtain the 10 most frequent cited first authors:
CR <- citations(M, field = "author", sep = ";")
cbind(CR$Cited[1:10])

```

```{r, include = TRUE, echo=FALSE}
print("The frequency table of the most local cited authors")
#the frequency table of the most local cited authors. Local means in the data collection.
CR <- localCitations(M, sep = ";")
CR$Authors[1:10,]

print("The frequency table of the most local cited papers")
CR$Papers[1:10,]
```

```{r, include = TRUE, echo=FALSE}
print("Authors’ Dominance ranking")
DF <- dominance(results, k = 10)
DF
```

```{r, include = TRUE, echo=FALSE}
# The h-index is an author-level metric that attempts to measure both the productivity and citation impact of the publications of a scientist or scholar.

indices <- Hindex(M, field = "author", elements="CHEN X", sep = ";", years = 10)
                                        # surname and initials are separated by one blank space
                                        # it could be a vector
print("Authors’ h-index")
indices$H
print("Authors’ citations")
indices$CitationList
```

```{r, include = TRUE, echo=FALSE}
# To calculate the h-index of the first 10 most productive authors (in this collection):
authors=gsub(","," ",names(results$Authors)[1:10])

indices <- Hindex(M, field = "author", elements=authors, sep = ";", years = 50)
print("The h-index of the first 10 most productive authors (in this collection)")
indices$H
```

```{r, include = TRUE, echo=FALSE}
# Top 10 Authors’ Productivity over the Time
# topAU <- authorProdOverTime(M, k = 10, graph = TRUE)
# this function may not work due to missing values
```

```{r, include = TRUE, echo=FALSE}
# analysis argument can be “co-citation”, “coupling”, “collaboration”, or “co-occurrences”.
# 
# network argument can be “authors”, “references”, “sources”, “countries”, “universities”, “keywords”, “author_keywords”, “titles” and “abstracts”.
print("References' Coupling")
NetMatrix <- biblioNetwork(M, analysis = "coupling", network = "references", sep = ";")
net=networkPlot(NetMatrix,  normalize = "salton", weighted=NULL, n = 100, Title = "References' Coupling", type = "fruchterman", size=5,size.cex=T,remove.multiple=TRUE,labelsize=0.8,label.n=10,label.cex=F)
```

```{r, include = TRUE, echo=FALSE}
netstat <- networkStat(NetMatrix)
print("Net work status")
# k is a formatting value that indicates the number of rows of each table
summary(netstat, k=10)
```

```{r, include = TRUE, echo=FALSE}
print("Country Collaboration")
M <- metaTagExtraction(M, Field = "AU_CO", sep = ";")
NetMatrix <- biblioNetwork(M, analysis = "collaboration", network = "countries", sep = ";")
net=networkPlot(NetMatrix, n = dim(NetMatrix)[1], Title = "Country Collaboration", type = "circle", size=TRUE, remove.multiple=FALSE,labelsize=0.7,cluster="none")

```

```{r, include = TRUE, echo=FALSE}
print("Co-Citation Network")
NetMatrix <- biblioNetwork(M, analysis = "co-citation", network = "references", sep = ";")

# Plot the network
net=networkPlot(NetMatrix, n = 30, Title = "Co-Citation Network", type = "fruchterman", size=T, remove.multiple=FALSE, labelsize=0.7,edgesize = 5)

```

```{r, include = TRUE, echo=FALSE}
print("Keyword Co-occurrences Network")

NetMatrix <- biblioNetwork(M, analysis = "co-occurrences", network = "keywords", sep = ";")

# Plot the network
net=networkPlot(NetMatrix, normalize="association", weighted=T, n = 30, Title = "Keyword Co-occurrences", type = "fruchterman", size=T,edgesize = 5,labelsize=0.7)
```

```{r, include = TRUE, echo=FALSE}
CS <- conceptualStructure(M,field="ID", method="CA", minDegree=4, clust=5, stemming=FALSE, labelsize=10, documents=10)
```

```{r}

```

