
```{r setup, include=TRUE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r}
packages <- c("tm"，        # for text mining
              "SnowballC"， # for text stemming
              "wordcloud"， # word-cloud generator 
              "RColorBrewer") # color palettes
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))
  lapply(packages, library, character.only = TRUE)
} else {
  lapply(packages, library, character.only = TRUE)
}


#Add patterns want to ingored
ignored_patterens <- c("/", "@", "\\|")
```


```{r}

text <- readLines(file.choose())

# Load the data as a corpus
docs <- Corpus(VectorSource(text))

inspect(docs) 

for (i in 1:length(ignored_patterens)) {
  toSpace <- content_transformer(function (x , pattern ) gsub(pattern, " ", x))
  tm_map(docs, toSpace, paste(ignored_patterens[i]))
  }
remove(toSpace)

# Convert the text to lower case
docs <- tm_map(docs, content_transformer(tolower))
# Remove numbers
docs <- tm_map(docs, removeNumbers)
# Remove english common stopwords
docs <- tm_map(docs, removeWords, stopwords("english"))
# Remove your own stop word
# specify your stopwords as a character vector
docs <- tm_map(docs, removeWords, c("blabla1", "blabla2")) 
# Remove punctuations
docs <- tm_map(docs, removePunctuation)
# Eliminate extra white spaces
docs <- tm_map(docs, stripWhitespace)
# Text stemming
# docs <- tm_map(docs, stemDocument)
 

dtm <- TermDocumentMatrix(docs)
m <- as.matrix(dtm)
v <- sort(rowSums(m),decreasing=TRUE)
d <- data.frame(word = names(v),freq=v)
head(d, 10)
 
set.seed(1234)
wordcloud(words = d$word, freq = d$freq, min.freq = 1,
          max.words=200, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))
```





